#' setCohortTypes
#'
#' Creates a data.frame to be used as the `cohorts` argument in `computePathways()`.
#'
#' @param x (`data.frame`) Either a `data.frame` that is filled with records
#' from `CohortGenerator::createEmptyCohortDefinitionSet()` or
#' `CohortGenerator::generateCohortSet()`; or a `CohortSet` generated by
#' `CDMConnector::readCohortSet()`
#' @param types (`character(n)`) A character vector with the types. Must
#' contain a selection of: `"target"`, `"event"`, or `"exit"`. The length of
#' the vector must be equal to the number of rows in `x`
#'
#' @returns `data.frame`
#' @export
#'
#' @examples {
#' if (interactive()) {
#'   cohorts <- setCohortTypes(cohortSet, types = c(rep("event", 7), "target"))
#'   cohorts <- setCohortTypes(cohortsGenerated, types = c("target", rep("event", 7)))
#'   cohorts <- setCohortTypes(cohortsToCreate, types = c("target", rep("event", 7)))
#' }
#' }
setCohortTypes <- function(x, types) {
  UseMethod("setCohortTypes")
}

#' @export
setCohortTypes.data.frame <- function(x, types) {
  assertions <- checkmate::makeAssertCollection()
  checkmate::assertNames(names(x), must.include = c("cohortId", "cohortName"), add = assertions)
  checkmate::assertTRUE(length(types) == nrow(x), add = assertions)
  checkmate::reportAssertions(assertions)

  x |>
    dplyr::select("cohortId", "cohortName") |>
    dplyr::mutate(type = types)
}

#' @export
setCohortTypes.CohortSet <- function(x, types) {
  assertions <- checkmate::makeAssertCollection()
  checkmate::assertNames(names(x), must.include = c("cohort_definition_id", "cohort_name"), add = assertions)
  checkmate::assertTRUE(length(types) == nrow(x), add = assertions)
  checkmate::reportAssertions(assertions)

  x |>
    dplyr::select(
      cohortId = "cohort_definition_id",
      cohortName = "cohort_name"
    ) |>
    dplyr::mutate(type = types)
}
