on:
  schedule:
    - cron: '0 8 * * 6'
  push:
    branches: [main, rc, dev, 292]

name: Big Query

jobs:
  Big-Query-test:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}
    env:
      STATUS: 0
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

      DBMS: 'bigquery'

      CONNECTION_STRING: ${{ secrets.BIG_QUERY_CONNECTION_STRING }}
      KEY_FILE: ${{ secrets.BIG_QUERY_KEY_FILE}}

      CDM_SCHEMA: ${{ secrets.BIG_QUERY_CDM_SCHEMA }}
      RESULT_SCHEMA: ${{ secrets.BIG_QUERY_RESULT_SCHEMA  }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          extra-repositories: 'https://OHDSI.github.io/drat'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"all"'

      - name: Install TreatmentPatterns
        run: R CMD INSTALL --with-keep.source --no-multiarch ./

      - name: Setup key-file
        run: |
          writeLines(Sys.getenv("CDM_BIG_QUERY_KEY_FILE"), "key_file.json")
        shell: Rscript{0}

      - name: Run test-database.R
        run: |
          Rscript -e 'testthat::test_file(
            path = "./tests/testthat/test-database.R",
            reporter = c("summary", "fail"),
            package = "TreatmentPatterns"
          )'