on:
  push:
    branches: [main]

name: Snowflake

jobs:
  Snowflake-test:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}
    env:
      STATUS: 0
      DATABASE: 'snowflake'
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      SNOWFLAKE_CDM_SCHEMA: ${{ secrets.SNOWFLAKE_CDM_SCHEMA }}
      SNOWFLAKE_RESULT_SCHEMA: ${{ secrets.SNOWFLAKE_RESULT_SCHEMA }}
      SNOWFLAKE_CONNECTION_STRING: ${{ secrets.SNOWFLAKE_CONNECTION_STRING }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      
      - name: list files
        run: ls -lah

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          extra-repositories: 'https://OHDSI.github.io/drat'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"all"'

      - name: Install TreatmentPatterns
        run: R CMD INSTALL --with-keep.source --no-multiarch ./

      - name: Run test-database.R
        run: |
          tryCatch({
            testthat::test_file(package = "TreatmentPatterns", path = "./tests/testthat/test-database.R")
          }, error = function(e) {
            Sys.setenv(STATUS = 1)
          })
        shell: Rscript {0}
        
      - name: Report status
        run: exit $STATUS