on:
  schedule:
    - cron: '0 8 * * 6'

name: Spark

jobs:
  CDMConnector-SQLServer-test:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}
    env:
      STATUS: 0
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

      USER: ${{ secrets.SPARK_USER }}
      PASSWORD: ${{ secrets.SPARK_PASSWORD }}
      WORKSPACE: ${{ secrets.SPARK_WORKSPACE}}
      HTTP_PATH: ${{ secrets.SPARK_HTTP_PATH}}

      CDM_SCHEMA: ${{ secrets.SPARK_CDM_SCHEMA }}
      RESULT_SCHEMA: ${{ secrets.SPARK_RESULT_SCHEMA }}

      DRIVER_PKG: 'odbc'

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          extra-repositories: 'https://OHDSI.github.io/drat'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"all"'

      - name: Install unixODBC
        run: sudo apt-get install unixodbc unixodbc-dev

      - name: Install odbcinst
        run: sudo apt-get install odbcinst
        
      - name: Fix symlink
        run: sudo ln -s /usr/lib/x86_64-linux-gnu/libodbcinst.so.2 /usr/lib/x86_64-linux-gnu/libodbcinst.so.1

      - name: Run odbc inst
        run: odbcinst -j

      - name: Download Driver
        run: wget https://databricks-bi-artifacts.s3.us-east-2.amazonaws.com/simbaspark-drivers/odbc/2.9.1/SimbaSparkODBC-2.9.1.1001-Debian-64bit.zip
      
      - name: unzip
        run: unzip SimbaSparkODBC-2.9.1.1001-Debian-64bit.zip

      - name: install odbc dependencies
        run: sudo apt-get install libsasl2-modules-gssapi-mit

      - name: Install Snowflake Driver
        run: sudo dpkg -i simbaspark_2.9.1.1001-2_amd64.deb

      - name: odbcinst.ini
        run: cat /etc/odbcinst.ini

      - name: odbcini
        run: cat /etc/odbc.ini

      - name: Install Driver Package
        run: install.packages("odbc")
        shell: Rscript {0}

      - name: Install TreatmentPatterns
        run: R CMD INSTALL --with-keep.source --no-multiarch ./

      - name: Connection Args
        run: |
          saveRDS(
            object = list(
              odbc::databricks(),
              httpPath = Sys.getenv("HTTP_PATH"),
              workspace = Sys.getenv("WORKSPACE"),
              uid = Sys.getenv("USER"),
              pwd = Sys.getenv("PASSWORD")            
            ),
            file = "./args.rds"
          )
        shell: Rscript {0}

      - name: Run test-database.R
        run: |
          Rscript -e 'testthat::test_file(
            path = "./extras/database_tests/CDMConnector-odbc.R",
            reporter = c("summary", "fail"),
            package = "TreatmentPatterns"
          )'