# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [master, rc, dev]
  pull_request:
    branches: [master, rc, dev]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install Linux jre and jdk
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y default-jre
          sudo apt-get install -y default-jdk
          sudo R CMD javareconf
        
      - name: Install Suggests
        run: |
            install.packages("knitr", repos = "https://cloud.r-project.org/")
            install.packages("rmarkdown", repos = "https://cloud.r-project.org/")
            install.packages("tibble", repos = "https://cloud.r-project.org/")
            install.packages("testthat", repos = "https://cloud.r-project.org/")
            install.packages("usethis")
            install.packages("CDMConnector")
            install.packages("DBI")
            install.packages("duckdb")
            install.packages("withr")
            install.packages("DatabaseConnector")
            install.packages("SqlRender")
            install.packages("rjson")
            install.packages("Andromeda")
            install.packages("googleVis")
            install.packages("sunburstR")
            install.packages("networkD3")
            install.packages("htmlwidgets")
        shell: Rscript {0}
        
        
      - name: Install CirceR
        run: |
            install.packages("rJava", repos = "https://cloud.r-project.org/")
            install.packages("RJSONIO", repos = "https://cloud.r-project.org/")
            install.packages("CirceR", repos = "https://OHDSI.github.io/drat", type = "source")
        shell: Rscript {0}
      
      - name: Install Eunomia
        run: |
            install.packages("SqlRender", repos = "https://cloud.r-project.org/")
            install.packages("RSQLite", repos = "https://cloud.r-project.org/")
            install.packages("readr", repos = "https://cloud.r-project.org/")
            install.packages("urltools", repos = "https://cloud.r-project.org/")
            install.packages("dbplyr", repos = "https://cloud.r-project.org/")
            install.packages("Eunomia", repos = "https://OHDSI.github.io/drat", type = "source")
        shell: Rscript {0}

      - name: Install CohortGenerator
        run: |
            install.packages("checkmate", repos = "https://cloud.r-project.org/")
            install.packages("digest", repos = "https://cloud.r-project.org/")
            install.packages("dplyr", repos = "https://cloud.r-project.org/")
            install.packages("lubridate", repos = "https://cloud.r-project.org/")
            install.packages("ParallelLogger", repos = "https://cloud.r-project.org/")
            install.packages("readr", repos = "https://cloud.r-project.org/")
            install.packages("rlang", repos = "https://cloud.r-project.org/")
            install.packages("RJSONIO", repos = "https://cloud.r-project.org/")
            install.packages("jsonlite", repos = "https://cloud.r-project.org/")
            install.packages("SqlRender", repos = "https://cloud.r-project.org/")
            install.packages("stringi", repos = "https://cloud.r-project.org/")

            install.packages("CohortGenerator", repos = "https://OHDSI.github.io/drat", type = "source")
        shell: Rscript {0}

      - name: Test coverage
        run: |
          covr::codecov(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
          )
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
