on:
  push:
    branches: [292]

name: Snowflake

jobs:
  Snowflake-test:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          extra-repositories: 'https://OHDSI.github.io/drat'

      - name: Fail from R
        run: |
          if Rscript -e 'stop("error")'
          then
            echo passed
            exit 0
          else
            echo failed
            exit 1
          fi